version: 2
updates:
- package-ecosystem: docker
  directory: "/alpine"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/debian"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/11/windows/nanoserver-ltsc2019"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/11/windows/windowsservercore-ltsc2019"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  target-branch: master
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
